### ISSUE TITLE
Not working with Pace IPH800 / IPH805 devices

### ISSUE THREAD

**Issue by equake** [dgomes/pymediaroom#1]
Hi Diogo!

My Mediaroom STB doesn't have port 8082 exposed
```
Starting Nmap 7.60 ( https://nmap.org ) at 2018-01-27 13:31 -02
Nmap scan report for 192.168.16.250
Host is up (0.036s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
8086/tcp open  d-s-n
```
It's not going to work, right?

Thanks!

**Comment by dgomes** [comment]
Hello Marcos,

You don't happen to have one of the "new" 4K set-top boxes ?

Can you test what 8086 is used for ? just "telnet ip_stb 8086" and type "key=33" (channel should change)

**Comment by equake** [comment]
Hi! Thanks for the quick response.

It does nothing
```
$ telnet 192.168.16.250 8086
Trying 192.168.16.250...
Connected to 192.168.16.250.
Escape character is '^]'.
key=33
key=33
```
As far as I can tell, it's an old device. It's not 4k.
https://drive.google.com/file/d/1MrjdnP7PygVNDqzqyGUB1fG7u-PSLkTh/view?usp=sharing
https://drive.google.com/file/d/1dOK053TKb92SDQCAjGJfuekr7uJvj6JZ/view?usp=sharing

I've tried to run `app.py` and, after changing the port to `8086` when instantiating the Remote class, I get this response:
```
$ python app.py 
�[{�6�r}��NOTIFY * HTTP/1.1�F�P���J!1�� ��z�ˎ音
x-type: display
x-filter: 1277b847-8aa6-49cb-bc1f-1d79fbaa0194
x-lastUserActivity: 1/11/2018 4:02:47 AM
x-location: http://192.168.16.250:8080/dvrfs/info.xml
x-device: 0f881f05-4b9b-4603-8926-541a95303d06
x-debug: http://192.168.16.250:8080

<node count='571179'><activities><p15n stamp='08D339F34B0B74907085C6A24E27'/><schedver dver='3' ver='5995' pendcap='False' /><x/></activities></node>
DEBUG:pymediaroom:('192.168.16.250', 1055)
INFO:root:Found 192.168.16.250
INFO:pymediaroom:Connected to 192.168.16.250:8086
DEBUG:pymediaroom:7�����I�F�P���J!1�� ��-o-S���g�����'��UNOTIFY * HTTP/1.1
x-type: display
x-filter: 1277b847-8aa6-49cb-bc1f-1d79fbaa0194
x-lastUserActivity: 1/11/2018 4:02:47 AM
x-location: http://192.168.16.250:8080/dvrfs/info.xml
x-device: 0f881f05-4b9b-4603-8926-541a95303d06
x-debug: http://192.168.16.250:8080

<node count='571182'><activities><p15n stamp='08D339F34B0B74907085C6A24E27'/><schedver dver='3' ver='5995' pendcap='False' /><x/></activities></node>
DEBUG:pymediaroom:('192.168.16.250', 1055)
INFO:root:STB is in Standby
INFO:pymediaroom:Disconnected
```

Thanks for your help! Obrigado!

**Comment by dgomes** [comment]
Your operator is Vivo in brazil. Never tested with those boxes...

Do you have a mobile application from the operator that you can use to change channels ?

**Comment by equake** [comment]
Yep I have, great idea.
It's the worst app imaginable. 

It seems to be sending some encoded/binary data to port 53208
https://drive.google.com/file/d/1FRlIkiH_yIFiZDiPEEku_if9wxbcg1Bj/view?usp=sharing

For the remote control to work I have to "pair" my cellphone with my STB. Requests seem to be signed based on this pairing... :(

**Comment by dgomes** [comment]
This uses a completely different protocol :( 

Will not be able to assist you...
