### ISSUE TITLE
Version mis-match

### ISSUE THREAD

**Issue by fabaff** [dgomes/pymediaroom#10]
https://github.com/dgomes/pymediaroom/blob/39e2a68778e7b4a68b35a0b92377166abd70273f/pymediaroom/__init__.py#L6

https://github.com/dgomes/pymediaroom/blob/39e2a68778e7b4a68b35a0b92377166abd70273f/setup.py#L6

https://github.com/dgomes/pymediaroom/releases/tag/0.6.4.1

It would be nice it they are aligned. Thanks.

**Comment by dgomes** [comment]
This project sure needs some ❤️  😅 

Will fix this!
