### ISSUE TITLE
Supported devices list anywhere?

### ISSUE THREAD

**Issue by pmpinto** [dgomes/pymediaroom#12]
Hey Diogo!
Thanks for this. I'm looking to integrate this in home assistant but I'm lacking some info regarding supported devices. Wondering if mine is even supported at all since I can't find a list anywhere. 

Mine is a Sagemcom DI362-UHD. Also known as the VBox 4K from Vodafone, if I'm not mistaken. 

What kind of actions would I be able to do?
Thanks!

**Comment by dgomes** [comment]
Olá :)

Esta biblioteca funciona apenas com a plataforma mediaroom que hoje em dia foi quase toda substituída.

As VBox 4k da Vodafone por exemplo não usam Mediaroom... (sei pq tenho uma)

Sorry :(

**Comment by pmpinto** [comment]
Pois, imaginei que sim. Já tinha perdido algum tempo mas não tinha chegado a conseguir fazer nada. Ainda bem que não perdi mais. 

Agradecido.

**Comment by pmpinto** [comment]
Já agora, consegues ter a tua box no HA de alguma forma?

**Comment by dgomes** [comment]
Não :( mas também não perdi muito tempo com isso, hoje em dia é mais plataformas de streaming 😓 

Mas o comando é bluetooth, ha boas chances de ser possivel controlar por ai...
