### ISSUE TITLE
Documenting known working set top boxes

### ISSUE THREAD

**Issue by ruimarinho** [dgomes/pymediaroom#3]
@dgomes which Portuguese set top boxes are known to work with this module? MEO + Vodafone (Arris)?

**Comment by dgomes** [comment]
Well I could use that feedback :)

I've got reports of:

* Vodafone (Arris)
* Meo (Cisco)

**Comment by rcarmo** [comment]
This is mostly working for me (after some tweaks) with:

* Vodafone (Cisco, compact STB)
* Vodafone (Technicolor, compact diskless STB)

Right now I've only tested (and fixed, at least for me) status monitoring, and a couple of basic commands. I plan to integrate with `homebridge` via MQTT, and am just getting started...

**Comment by migromao** [comment]
Hi, on the MEO box - new firmware March2018

I've installed this in the Home Assistant but its not displaying the remote functions.
its just shows the typical media_player component functions but no channel, no visibility on live, recording, etc playing .. not any list of channels .

any guidance on how to achieve ?

**Comment by dgomes** [comment]
@migromao you should open a new issue, this is not a chatroom ;)

Currently none of those features are supported in Home Assistant (main developers don't want to add channels to the media_player interface, and status is not a content they wish to display)

**Comment by ruimarinho** [comment]
Thanks everyone. I think this is good enough for now.
