### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Power535** [dgomes/pymediaroom#7]
closed

**Comment by dgomes** [comment]
?

**Comment by Power535** [comment]
USB possible off in cfe
Possible replace cfe via tftp or dhcp ?

**Comment by dgomes** [comment]
This project does not involve any tinkering of the box.

**Comment by Power535** [comment]
Question for media room
I try run Linux few years
Only do not know as replace bootloader or kernel
If you can help , please your message

**Comment by dgomes** [comment]
That is out of scope of this project.
